### ISSUE TITLE
I can't send you a DM, so I reach out here

### ISSUE THREAD

**Issue by donzec** [Exfil-Finance/exfil-bridge#1]
Hey Exfil-Team,

I just saw your video from ETH-Global and think it's super interesting what you've built with Exfil. Are you looking to continue the project? If yes, it would be great to jump on a call and exchange thoughts! Slots that fit me: https://calendly.com/donze/hi

My name's Claude, I'm with Tomahawk.VC, we're investing in DeFi and more general applications in the Ethereum ecosystem. More background at https://www.tomahawk.vc/

Claude

**Comment by barrasso** [comment]
Just sent you an email. Thanks for reaching out, Claude!
